version: "3"
 
services:
 
  master:
    image: johnydickens/openmpi:v3
    entrypoint: /bin/bash
    links:
      - nodo1
      - nodo2
    networks:
      - mpi
    stdin_open: true
    tty: true
    
  nodo1:
    image: johnydickens/openmpi:v3
    entrypoint: /bin/bash
    networks:
      - mpi
    stdin_open: true
    tty: true

  nodo2:
    image: johnydickens/openmpi:v3
    entrypoint: /bin/bash
    networks:
      - mpi
    stdin_open: true
    tty: true

      
networks:
  mpi:
    external: true